// packages/dev-server/test-plugins/experimental-ui/components/SlugWithLink.tsx
import { ReactDataTableComponentProps } from '@vendure/admin-ui/react';
import React from 'react';

export function SlugWithLink({ rowItem }: ReactDataTableComponentProps) {
    const slug: string = rowItem.slug;
    return (
        <a href={`https://example.com/category/${slug}`} target="_blank">
            {slug}
        </a>
    );
}

// packages/dev-server/test-plugins/experimental-ui/components/slug-with-link.component.ts
import { Component, Input } from '@angular/core';
import { CustomColumnComponent } from '@vendure/admin-ui/core';

@Component({
    selector: 'slug-with-link',
    template: `
        <a [href]="'https://example.com/products/' + rowItem.slug" target="_blank">{{ rowItem.slug }}</a>
    `,
    standalone: true,
})
export class SlugWithLinkComponent implements CustomColumnComponent {
    @Input() rowItem: any;
}
