// packages/admin-ui/src/lib/core/src/shared/components/asset-preview/asset-preview.component.ts
import {
    ChangeDetectionStrategy,
    ChangeDetectorRef,
    Component,
    ElementRef,
    EventEmitter,
    Input,
    OnDestroy,
    OnInit,
    Output,
    ViewChild,
} from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { marker as _ } from '@biesbjerg/ngx-translate-extract-marker';
import { fromEvent, Subscription } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

import { GetAsset, GetAssetList, UpdateAssetInput } from '../../../common/generated-types';
import { DataService } from '../../../data/providers/data.service';
import { NotificationService } from '../../../providers/notification/notification.service';
import { Point } from '../focal-point-control/focal-point-control.component';

export type PreviewPreset = 'tiny' | 'thumb' | 'small' | 'medium' | 'large' | '';
type AssetLike = GetAssetList.Items | GetAsset.Asset;

@Component({
    selector: 'vdr-asset-preview',
    templateUrl: './asset-preview.component.html',
    styleUrls: ['./asset-preview.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AssetPreviewComponent implements OnInit, OnDestroy {
    @Input() asset: AssetLike;
    @Input() editable = false;
    @Output() assetChange = new EventEmitter<Omit<UpdateAssetInput, 'focalPoint'>>();
    @Output() editClick = new EventEmitter();

    form: FormGroup;

    size: PreviewPreset = 'medium';
    width = 0;
    height = 0;
    centered = true;
    settingFocalPoint = false;
    lastFocalPoint?: Point;
    @ViewChild('imageElement', { static: true }) private imageElementRef: ElementRef<HTMLImageElement>;
    @ViewChild('previewDiv', { static: true }) private previewDivRef: ElementRef<HTMLDivElement>;
    private subscription: Subscription;
    private sizePriorToSettingFocalPoint: PreviewPreset;

    constructor(
        private formBuilder: FormBuilder,
        private dataService: DataService,
        private notificationService: NotificationService,
        private changeDetector: ChangeDetectorRef,
    ) {}

    get fpx(): number | null {
        return this.asset.focalPoint ? this.asset.focalPoint.x : null;
    }

    get fpy(): number | null {
        return this.asset.focalPoint ? this.asset.focalPoint.y : null;
    }

    ngOnInit() {
        const { focalPoint } = this.asset;
        this.form = this.formBuilder.group({
            name: [this.asset.name],
            tags: [this.asset.tags?.map(t => t.value)],
        });
        this.subscription = this.form.valueChanges.subscribe(value => {
            this.assetChange.emit({
                id: this.asset.id,
                name: value.name,
                tags: value.tags,
            });
        });

        this.subscription.add(
            fromEvent(window, 'resize')
                .pipe(debounceTime(50))
                .subscribe(() => {
                    this.updateDimensions();
                    this.changeDetector.markForCheck();
                }),
        );
    }

    ngOnDestroy(): void {
        if (this.subscription) {
            this.subscription.unsubscribe();
        }
    }

    getSourceFileName(): string {
        const parts = this.asset.source.split('/');
        return parts[parts.length - 1];
    }

    onImageLoad() {
        this.updateDimensions();
        this.changeDetector.markForCheck();
    }

    updateDimensions() {
        const img = this.imageElementRef.nativeElement;
        const container = this.previewDivRef.nativeElement;
        const imgWidth = img.naturalWidth;
        const imgHeight = img.naturalHeight;
        const containerWidth = container.offsetWidth;
        const containerHeight = container.offsetHeight;

        const constrainToContainer = this.settingFocalPoint;
        if (constrainToContainer) {
            const controlsMarginPx = 48 * 2;
            const availableHeight = containerHeight - controlsMarginPx;
            const availableWidth = containerWidth;
            const hRatio = imgHeight / availableHeight;
            const wRatio = imgWidth / availableWidth;

            const imageExceedsAvailableDimensions = 1 < hRatio || 1 < wRatio;
            if (imageExceedsAvailableDimensions) {
                const factor = hRatio < wRatio ? wRatio : hRatio;
                this.width = Math.round(imgWidth / factor);
                this.height = Math.round(imgHeight / factor);
                this.centered = true;
                return;
            }
        }
        this.width = imgWidth;
        this.height = imgHeight;
        this.centered = imgWidth <= containerWidth && imgHeight <= containerHeight;
    }

    setFocalPointStart() {
        this.sizePriorToSettingFocalPoint = this.size;
        this.size = 'medium';
        this.settingFocalPoint = true;
        this.lastFocalPoint = this.asset.focalPoint || { x: 0.5, y: 0.5 };
        this.updateDimensions();
    }

    removeFocalPoint() {
        this.dataService.product
            .updateAsset({
                id: this.asset.id,
                focalPoint: null,
            })
            .subscribe(
                () => {
                    this.notificationService.success(_('asset.update-focal-point-success'));
                    this.asset = { ...this.asset, focalPoint: null };
                    this.changeDetector.markForCheck();
                },
                () => this.notificationService.error(_('asset.update-focal-point-error')),
            );
    }

    onFocalPointChange(point: Point) {
        this.lastFocalPoint = point;
    }

    setFocalPointCancel() {
        this.settingFocalPoint = false;
        this.lastFocalPoint = undefined;
        this.size = this.sizePriorToSettingFocalPoint;
    }

    setFocalPointEnd() {
        this.settingFocalPoint = false;
        this.size = this.sizePriorToSettingFocalPoint;
        if (this.lastFocalPoint) {
            const { x, y } = this.lastFocalPoint;
            this.lastFocalPoint = undefined;
            this.dataService.product
                .updateAsset({
                    id: this.asset.id,
                    focalPoint: { x, y },
                })
                .subscribe(
                    () => {
                        this.notificationService.success(_('asset.update-focal-point-success'));
                        this.asset = { ...this.asset, focalPoint: { x, y } };
                        this.changeDetector.markForCheck();
                    },
                    () => this.notificationService.error(_('asset.update-focal-point-error')),
                );
        }
    }
}

<vdr-page-detail-layout>
    <vdr-page-detail-sidebar>
        <vdr-card>
            <div *ngIf="!editable" class="mb-2">
                <a
                    class="button-ghost"
                    [routerLink]="['/catalog', 'assets', asset.id]"
                    (click)="editClick.emit()"
                >
                    <clr-icon shape="edit"></clr-icon>
                    {{ 'common.edit' | translate }}
                    <clr-icon shape="arrow right"></clr-icon>
                </a>
            </div>
            <vdr-form-field *ngIf="editable" [label]="'common.name' | translate" class="mb-2">
                <input
                    type="text"
                    [formControl]="form.get('name')"
                    [readonly]="!(['UpdateCatalog', 'UpdateAsset'] | hasPermission) || settingFocalPoint"
                />
            </vdr-form-field>
            <vdr-labeled-data [label]="'common.name' | translate" *ngIf="!editable">
                <span class="elide">
                    {{ asset.name }}
                </span>
            </vdr-labeled-data>
            <vdr-labeled-data [label]="'asset.source-file' | translate">
                <a [href]="asset.source" [title]="asset.source" target="_blank" class="elide source-link">{{
                    getSourceFileName()
                }}</a>
            </vdr-labeled-data>

            <vdr-labeled-data [label]="'asset.original-asset-size' | translate">
                {{ asset.fileSize | filesize }}
            </vdr-labeled-data>

            <vdr-labeled-data [label]="'asset.dimensions' | translate">
                {{ asset.width }} x {{ asset.height }}
            </vdr-labeled-data>

            <vdr-labeled-data [label]="'asset.focal-point' | translate">
                <span *ngIf="fpx"
                    ><clr-icon shape="crosshairs"></clr-icon> x: {{ fpx | number : '1.2-2' }}, y:
                    {{ fpy | number : '1.2-2' }}</span
                >
                <span *ngIf="!fpx">{{ 'common.not-set' | translate }}</span>
                <div class="flex mt-1">
                    <button
                        class="button-small mr-1"
                        [disabled]="settingFocalPoint"
                        (click)="setFocalPointStart()"
                    >
                        <ng-container *ngIf="!fpx">{{ 'asset.set-focal-point' | translate }}</ng-container>
                        <ng-container *ngIf="fpx">{{ 'asset.update-focal-point' | translate }}</ng-container>
                    </button>
                    <button
                        class="button-small"
                        [disabled]="settingFocalPoint"
                        *ngIf="!!fpx"
                        (click)="removeFocalPoint()"
                    >
                        {{ 'asset.unset-focal-point' | translate }}
                    </button>
                </div>
            </vdr-labeled-data>
            <vdr-labeled-data [label]="'common.tags' | translate">
                <ng-container *ngIf="editable">
                    <vdr-tag-selector [formControl]="form.get('tags')"></vdr-tag-selector>
                    <button class="button-small mt-1" (click)="manageTags()">
                        <clr-icon shape="tags"></clr-icon>
                        {{ 'common.manage-tags' | translate }}
                    </button>
                </ng-container>
                <div *ngIf="!editable">
                    <vdr-chip *ngFor="let tag of asset.tags" [colorFrom]="tag.value">
                        <clr-icon shape="tag" class="mr2"></clr-icon>
                        {{ tag.value }}</vdr-chip
                    >
                </div>
            </vdr-labeled-data>
        </vdr-card>
        <vdr-card *ngIf="customFields.length" [title]="'common.custom-fields' | translate">
            <vdr-tabbed-custom-fields
                entityName="Asset"
                [compact]="true"
                [customFields]="customFields"
                [customFieldsFormGroup]="customFieldsForm"
                [readonly]="!(['UpdateCatalog', 'UpdateAsset'] | hasPermission)"
            ></vdr-tabbed-custom-fields>
        </vdr-card>
        <vdr-card [title]="'asset.preview' | translate">
            <vdr-form-field>
                <select name="options" [(ngModel)]="size" [disabled]="settingFocalPoint">
                    <option value="tiny">tiny</option>
                    <option value="thumb">thumb</option>
                    <option value="small">small</option>
                    <option value="medium">medium</option>
                    <option value="large">large</option>
                    <option value="">full size</option>
                </select>
            </vdr-form-field>
            <div class="asset-detail">{{ width }} x {{ height }}</div>
            <vdr-asset-preview-links [asset]="asset"></vdr-asset-preview-links>
        </vdr-card>
        <vdr-card>
            <vdr-page-entity-info *ngIf="asset as entity" [entity]="entity"></vdr-page-entity-info>
        </vdr-card>
    </vdr-page-detail-sidebar>
    <div class="carousel-container">
        <button *ngIf="showSlideButtons" (click)="previousImage()" class="carousel-button" [class.disabled]="disablePreviousButton">
            <clr-icon shape="caret left" class="color-weight-800"></clr-icon>
        </button>
        <div class="preview-image" #previewDiv [class.centered]="centered">
            <div class="image-wrapper">
                <vdr-focal-point-control
                    [width]="width"
                    [height]="height"
                    [fpx]="fpx"
                    [fpy]="fpy"
                    [editable]="settingFocalPoint"
                    (focalPointChange)="onFocalPointChange($event)"
                >
                    <img
                        class="asset-image"
                        [src]="asset | assetPreview : size"
                        [ngClass]="size"
                        #imageElement
                        (load)="onImageLoad()"
                    />
                </vdr-focal-point-control>
                <div class="focal-point-info" *ngIf="settingFocalPoint">
                    <button class="icon-button" (click)="setFocalPointCancel()">
                        <clr-icon shape="times"></clr-icon>
                    </button>
                    <button
                        class="btn btn-primary btn-sm"
                        (click)="setFocalPointEnd()"
                        [disabled]="!lastFocalPoint"
                    >
                        <clr-icon shape="crosshairs"></clr-icon>
                        {{ 'asset.set-focal-point' | translate }}
                    </button>
                </div>
            </div>
        </div>
        <button *ngIf="showSlideButtons" (click)="nextImage()" class="carousel-button" [class.disabled]="disableNextButton">
            <clr-icon shape="caret right" class="color-weight-800"></clr-icon>
        </button>
    </div>
</vdr-page-detail-layout>

// packages/dashboard/src/components/shared/asset-preview.tsx
import { Button } from '@/components/ui/button.js';
import { Card, CardContent, CardHeader } from '@/components/ui/card.js';
import { FormControl, FormField, FormItem, FormLabel } from '@/components/ui/form.js';
import { Input } from '@/components/ui/input.js';
import { Label } from '@/components/ui/label.js';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select.js';
import { VendureImage } from '@/components/shared/vendure-image.js';
import { AssetFragment } from '@/graphql/fragments.js';
import { cn, formatFileSize } from '@/lib/utils.js';
import { ChevronLeft, ChevronRight, Crosshair, Edit, ExternalLink, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useForm } from 'react-hook-form';
import { FocalPointControl } from './focal-point-control.js';

export type PreviewPreset = 'tiny' | 'thumb' | 'small' | 'medium' | 'large' | '';

interface Point {
    x: number;
    y: number;
}

export type Asset = AssetFragment & { tags?: { value: string }[] };

interface AssetPreviewProps {
    asset: Asset;
    assets?: Asset[];
    editable?: boolean;
    customFields?: any[];
    onAssetChange?: (asset: Partial<Asset>) => void;
    onEditClick?: () => void;
}

export function AssetPreview({
    asset,
    assets,
    editable = false,
    customFields = [],
    onAssetChange,
    onEditClick,
}: AssetPreviewProps) {
    const [size, setSize] = useState<PreviewPreset>('medium');
    const [width, setWidth] = useState(0);
    const [height, setHeight] = useState(0);
    const [centered, setCentered] = useState(true);
    const [settingFocalPoint, setSettingFocalPoint] = useState(false);
    const [lastFocalPoint, setLastFocalPoint] = useState<Point>();
    const [assetIndex, setAssetIndex] = useState(assets?.indexOf(asset) || 0);

    const imageRef = useRef<HTMLImageElement>(null);
    const containerRef = useRef<HTMLDivElement>(null);
    const sizePriorToFocalPoint = useRef<PreviewPreset>('medium');

    const form = useForm({
        defaultValues: {
            name: asset.name,
            tags: asset.tags?.map(t => t.value) || [],
        },
    });
    const activeAsset = assets?.[assetIndex] ?? asset;

    useEffect(() => {
        if (assets?.length) {
            const index = assets.findIndex(a => a.id === asset.id);
            setAssetIndex(index === -1 ? 0 : index);
        }
    }, [assets, asset.id]);

    useEffect(() => {
        const handleResize = () => {
            updateDimensions();
        };

        window.addEventListener('resize', handleResize);
        return () => window.removeEventListener('resize', handleResize);
    }, []);

    const updateDimensions = () => {
        if (!imageRef.current || !containerRef.current) return;

        const img = imageRef.current;
        const container = containerRef.current;
        const imgWidth = img.naturalWidth;
        const imgHeight = img.naturalHeight;
        const containerWidth = container.offsetWidth;
        const containerHeight = container.offsetHeight;

        if (settingFocalPoint) {
            const controlsMarginPx = 48 * 2;
            const availableHeight = containerHeight - controlsMarginPx;
            const availableWidth = containerWidth;
            const hRatio = imgHeight / availableHeight;
            const wRatio = imgWidth / availableWidth;

            if (1 < hRatio || 1 < wRatio) {
                const factor = hRatio < wRatio ? wRatio : hRatio;
                setWidth(Math.round(imgWidth / factor));
                setHeight(Math.round(imgHeight / factor));
                setCentered(true);
                return;
            }
        }

        setWidth(imgWidth);
        setHeight(imgHeight);
        setCentered(imgWidth <= containerWidth && imgHeight <= containerHeight);
    };

    const handleFocalPointStart = () => {
        sizePriorToFocalPoint.current = size;
        setSize('medium');
        setSettingFocalPoint(true);
        setLastFocalPoint(asset.focalPoint || { x: 0.5, y: 0.5 });
        updateDimensions();
    };

    const handleFocalPointChange = (point: Point) => {
        setLastFocalPoint(point);
    };

    const handleFocalPointCancel = () => {
        setSettingFocalPoint(false);
        setLastFocalPoint(undefined);
        setSize(sizePriorToFocalPoint.current);
    };

    const handleFocalPointSet = async () => {
        if (!lastFocalPoint) return;

        try {
            // TODO: Implement API call to update focal point
            await onAssetChange?.({
                id: asset.id,
                focalPoint: lastFocalPoint,
            });
            setSettingFocalPoint(false);
            setSize(sizePriorToFocalPoint.current);
            // Show success toast
        } catch (err) {
            // Show error toast
        }
    };

    const handleRemoveFocalPoint = async () => {
        try {
            // TODO: Implement API call to remove focal point
            await onAssetChange?.({
                id: asset.id,
                focalPoint: null,
            });
            // Show success toast
        } catch (err) {
            // Show error toast
        }
    };

    return (
        <div className="grid grid-cols-1 md:grid-cols-[300px_1fr] gap-4 h-full">
            <div className="space-y-4">
                <Card>
                    <CardContent className="space-y-4 pt-6">
                        {!editable && onEditClick && (
                            <Button variant="ghost" className="w-full justify-start" onClick={onEditClick}>
                                <Edit className="mr-2 h-4 w-4" />
                                Edit
                                <ChevronRight className="ml-auto h-4 w-4" />
                            </Button>
                        )}

                        {editable ? (
                            <FormField
                                control={form.control}
                                name="name"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Name</FormLabel>
                                        <FormControl>
                                            <Input {...field} />
                                        </FormControl>
                                    </FormItem>
                                )}
                            />
                        ) : (
                            <div>
                                <Label>Name</Label>
                                <p className="truncate text-sm text-muted-foreground">{activeAsset.name}</p>
                            </div>
                        )}

                        <div>
                            <Label>Source File</Label>
                            <a
                                href={activeAsset.source}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-sm text-primary hover:underline flex items-center"
                            >
                                {activeAsset.source.split('/').pop()}
                                <ExternalLink className="ml-1 h-3 w-3" />
                            </a>
                        </div>

                        <div>
                            <Label>File Size</Label>
                            <p className="text-sm text-muted-foreground">
                                {formatFileSize(activeAsset.fileSize)}
                            </p>
                        </div>

                        <div>
                            <Label>Dimensions</Label>
                            <p className="text-sm text-muted-foreground">
                                {activeAsset.width} x {activeAsset.height}
                            </p>
                        </div>

                        <div>
                            <Label>Focal Point</Label>
                            <div className="space-y-2">
                                <p className="text-sm text-muted-foreground">
                                    {activeAsset.focalPoint ? (
                                        <span className="flex items-center">
                                            <Crosshair className="mr-1 h-4 w-4" />
                                            x: {activeAsset.focalPoint.x.toFixed(2)}, y:{' '}
                                            {activeAsset.focalPoint.y.toFixed(2)}
                                        </span>
                                    ) : (
                                        'Not set'
                                    )}
                                </p>
                                <div className="flex gap-2">
                                    <Button
                                        variant="secondary"
                                        size="sm"
                                        disabled={settingFocalPoint}
                                        onClick={handleFocalPointStart}
                                    >
                                        {activeAsset.focalPoint ? 'Update' : 'Set'} Focal Point
                                    </Button>
                                    {activeAsset.focalPoint && (
                                        <Button
                                            variant="secondary"
                                            size="sm"
                                            disabled={settingFocalPoint}
                                            onClick={handleRemoveFocalPoint}
                                        >
                                            Remove
                                        </Button>
                                    )}
                                </div>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>Preview Options</CardHeader>
                    <CardContent className="space-y-4">
                        <Select value={size} onValueChange={value => setSize(value as PreviewPreset)}>
                            <SelectTrigger>
                                <SelectValue placeholder="Select size" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="tiny">Tiny</SelectItem>
                                <SelectItem value="thumb">Thumb</SelectItem>
                                <SelectItem value="small">Small</SelectItem>
                                <SelectItem value="medium">Medium</SelectItem>
                                <SelectItem value="large">Large</SelectItem>
                                <SelectItem value="full">Full Size</SelectItem>
                            </SelectContent>
                        </Select>
                        <p className="text-sm text-muted-foreground">
                            {width} x {height}
                        </p>
                    </CardContent>
                </Card>
            </div>

            <div className="relative flex items-center justify-center bg-muted/30 rounded-lg">
                {assets && assets.length > 1 && (
                    <>
                        <Button
                            variant="ghost"
                            size="icon"
                            className="absolute left-4 z-10"
                            onClick={() => setAssetIndex(i => i - 1)}
                            disabled={assetIndex === 0}
                        >
                            <ChevronLeft className="h-4 w-4" />
                        </Button>
                        <Button
                            variant="ghost"
                            size="icon"
                            className="absolute right-4 z-10"
                            onClick={() => setAssetIndex(i => i + 1)}
                            disabled={assetIndex === assets.length - 1}
                        >
                            <ChevronRight className="h-4 w-4" />
                        </Button>
                    </>
                )}

                <div
                    ref={containerRef}
                    className={cn(
                        'relative',
                        centered && 'flex items-center justify-center',
                        settingFocalPoint && 'cursor-crosshair',
                    )}
                >
                    <div className="relative" style={{ width: `${width}px`, height: `${height}px` }}>
                        <VendureImage
                            ref={imageRef}
                            asset={activeAsset}
                            preset={size || undefined}
                            mode="resize"
                            onLoad={updateDimensions}
                            className="max-w-full max-h-full object-contain"
                        />
                        {settingFocalPoint && lastFocalPoint && (
                            <FocalPointControl
                                width={width}
                                height={height}
                                point={lastFocalPoint}
                                onChange={handleFocalPointChange}
                            />
                        )}
                    </div>

                    {settingFocalPoint && (
                        <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2">
                            <Button variant="secondary" onClick={handleFocalPointCancel}>
                                <X className="mr-2 h-4 w-4" />
                                Cancel
                            </Button>
                            <Button onClick={handleFocalPointSet}>
                                <Crosshair className="mr-2 h-4 w-4" />
                                Set Focal Point
                            </Button>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
